# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fit_aerwnnet <- function(x, y, size, skip = TRUE, flat = TRUE, eta = 1.96) {
    .Call(`_rwnnet_fit_aerwnnet`, x, y, size, skip, flat, eta)
}

.predict_aerwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_aerwnnet`, network, x)
}

.fit_drwnnet <- function(x, y, size, eta = 1.96) {
    .Call(`_rwnnet_fit_drwnnet`, x, y, size, eta)
}

.predict_drwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_drwnnet`, network, x)
}

.fit_edaerwnnet <- function(x, y, size, skip = TRUE, eta = 1.96) {
    .Call(`_rwnnet_fit_edaerwnnet`, x, y, size, skip, eta)
}

.predict_edaerwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_edaerwnnet`, network, x)
}

.fit_edrwnnet <- function(x, y, size, eta = 1.96) {
    .Call(`_rwnnet_fit_edrwnnet`, x, y, size, eta)
}

.predict_edrwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_edrwnnet`, network, x)
}

.fit_r2rwnnet <- function(x, y, size, skip = TRUE, eta = 1.96) {
    .Call(`_rwnnet_fit_r2rwnnet`, x, y, size, skip, eta)
}

.predict_r2rwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_r2rwnnet`, network, x)
}

.fit_saerwnnet <- function(x, y, size, eta = 1.96) {
    .Call(`_rwnnet_fit_saerwnnet`, x, y, size, eta)
}

.predict_saerwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_saerwnnet`, network, x)
}

.fit_slrwnnet <- function(x, y, size, skip = TRUE, eta = 1.96) {
    .Call(`_rwnnet_fit_slrwnnet`, x, y, size, skip, eta)
}

.predict_slrwnnet <- function(network, x) {
    .Call(`_rwnnet_predict_slrwnnet`, network, x)
}

.tikhonov <- function(x, y) {
    .Call(`_rwnnet_tikhonov`, x, y)
}

